# Generated by Django 3.1.8 on 2021-07-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='card_number',
        ),
    ]
